#!/usr/bin/env python3
"""Build or verify the browser-loadable leaderboard history bundle."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

HEADER = "// Generated by scripts/kvcompress_leaderboard.py; do not edit.\n"


def render(history: Path) -> str:
    payload = json.loads(history.read_text(encoding="utf-8"))
    if payload.get("schema_version") != 1:
        raise ValueError("unsupported leaderboard history schema")
    records = payload.get("records")
    if not isinstance(records, list) or not records:
        raise ValueError("leaderboard history must contain records")
    identifiers = [record.get("id") for record in records]
    if any(not identifier for identifier in identifiers):
        raise ValueError("every leaderboard record requires an id")
    if len(set(identifiers)) != len(identifiers):
        raise ValueError("leaderboard record ids must be unique")
    serialized = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    return f"{HEADER}window.KV_LEADERBOARD_HISTORY={serialized};\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--history",
        type=Path,
        default=Path("docs/evidence/leaderboard-history.json"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/evidence/leaderboard-history.js"),
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(args.history)
    if args.check:
        output_matches = (
            args.output.is_file()
            and args.output.read_text(encoding="utf-8") == expected
        )
        if not output_matches:
            raise SystemExit(
                "leaderboard bundle is stale; run scripts/kvcompress_leaderboard.py"
            )
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
