#!/usr/bin/env python3
"""Build or verify the browser-loadable leaderboard history bundle."""

from __future__ import annotations

import argparse
import json
import math
import re
from pathlib import Path

HEADER = "// Generated by scripts/kvcompress_leaderboard.py; do not edit.\n"


def render(history: Path) -> str:
    payload = json.loads(history.read_text(encoding="utf-8"))
    if payload.get("schema_version") != 1:
        raise ValueError("unsupported leaderboard history schema")
    records = payload.get("records")
    if not isinstance(records, list) or not records:
        raise ValueError("leaderboard history must contain records")
    identifiers = [record.get("id") for record in records]
    if any(not identifier for identifier in identifiers):
        raise ValueError("every leaderboard record requires an id")
    if len(set(identifiers)) != len(identifiers):
        raise ValueError("leaderboard record ids must be unique")
    serialized = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    return f"{HEADER}window.KV_LEADERBOARD_HISTORY={serialized};\n"


def render_frontier(path: Path) -> str:
    """Render only measured Frontier points; never infer points from history."""
    payload = json.loads(path.read_text(encoding="utf-8"))
    if payload.get("schema_version") != "leaderboard-frontier/v1":
        raise ValueError("unsupported Frontier schema")
    cohorts, points = payload.get("cohorts"), payload.get("points")
    if not isinstance(cohorts, list) or not cohorts or not isinstance(points, list):
        raise ValueError("Frontier requires cohorts and a points list")
    cohort_ids = [cohort.get("id") for cohort in cohorts]
    if any(not value for value in cohort_ids) or len(cohort_ids) != len(
        set(cohort_ids)
    ):
        raise ValueError("Frontier cohort ids must be nonempty and unique")
    for cohort in cohorts:
        if (
            not cohort.get("model", {}).get("revision")
            or not cohort.get("workload", {}).get("id")
            or cohort.get("context_tokens", 0) < 262144
            or cohort.get("workload", {}).get("contract", {}).get("measurement_seconds")
            != 900
        ):
            raise ValueError("invalid Frontier cohort contract")
    point_ids = [point.get("id") for point in points]
    if any(not value for value in point_ids) or len(point_ids) != len(set(point_ids)):
        raise ValueError("Frontier point ids must be nonempty and unique")
    pairs: dict[str, list[dict]] = {}
    for point in points:
        config, metrics, evidence = (
            point.get("configuration", {}),
            point.get("metrics", {}),
            point.get("evidence", {}),
        )
        count = config.get("hardware", {}).get("accelerator_count")
        load = point.get("load", {})
        capacity = config.get("context_capacity_tokens")
        max_prompt = load.get("max_observed_prompt_tokens")
        url = evidence.get("url")
        safe_url = isinstance(url, str) and (
            url.startswith("https://")
            or (
                re.fullmatch(r"evidence/[A-Za-z0-9._/-]+\.json", url)
                and ".." not in Path(url).parts
            )
        )
        if (
            point.get("cohort_id") not in cohort_ids
            or not point.get("pair_id")
            or point.get("arm") not in ("B0", "B1")
            or not config.get("engine")
            or not config.get("hardware", {}).get("label")
            or not isinstance(config.get("mods"), list)
            or type(capacity) is not int
            or capacity < 262144
            or type(load.get("concurrency")) is not int
            or load["concurrency"] < 1
            or type(max_prompt) is not int
            or max_prompt < 1
            or evidence.get("status") != "measured"
            or not isinstance(evidence.get("run_ids"), list)
            or not evidence["run_ids"]
            or not evidence.get("aggregation")
            or evidence.get("measurement_seconds") != 900
            or not safe_url
            or type(count) is not int
            or count < 1
            or type(metrics.get("output_tps")) not in (int, float)
            or not math.isfinite(metrics["output_tps"])
            or metrics["output_tps"] <= 0
            or type(metrics.get("decode_p90_tps")) not in (int, float)
            or not math.isfinite(metrics["decode_p90_tps"])
            or metrics["decode_p90_tps"] <= 0
        ):
            raise ValueError(f"incomplete measured Frontier point: {point.get('id')}")
        pairs.setdefault(point["pair_id"], []).append(point)
    for pair_id, pair in pairs.items():
        if (
            len(pair) != 2
            or {point["arm"] for point in pair} != {"B0", "B1"}
            or len({point["cohort_id"] for point in pair}) != 1
            or len({point["load"]["concurrency"] for point in pair}) != 1
            or len(
                {
                    point["configuration"]["hardware"]["accelerator_count"]
                    for point in pair
                }
            )
            != 1
        ):
            raise ValueError(
                f"Frontier pair must contain comparable B0/B1 arms: {pair_id}"
            )
    serialized = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    return f"{HEADER}window.KV_FRONTIER_RESULTS={serialized};\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--history",
        type=Path,
        default=Path("docs/evidence/leaderboard-history.json"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/evidence/leaderboard-history.js"),
    )
    parser.add_argument(
        "--frontier",
        type=Path,
        default=Path("docs/evidence/frontier-results.json"),
    )
    parser.add_argument(
        "--frontier-output",
        type=Path,
        default=Path("docs/evidence/frontier-results.js"),
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(args.history)
    frontier_expected = render_frontier(args.frontier)
    if args.check:
        output_matches = (
            args.output.is_file()
            and args.output.read_text(encoding="utf-8") == expected
            and args.frontier_output.is_file()
            and args.frontier_output.read_text(encoding="utf-8") == frontier_expected
        )
        if not output_matches:
            raise SystemExit(
                "leaderboard bundle is stale; run scripts/kvcompress_leaderboard.py"
            )
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8")
    args.frontier_output.parent.mkdir(parents=True, exist_ok=True)
    args.frontier_output.write_text(frontier_expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
